runtime: python27
api_version: 1
threadsafe: true
automatic_scaling:
  max_idle_instances: 1


handlers:

- url: /client/assets
  static_dir: assets
  secure: always

- url: /assets
  static_dir: assets
  secure: always

- url: /$
  static_files: client/index_deploy.html
  upload: client/index_deploy.html
  secure: always

- url: /client/$
  static_files: client/index_deploy.html
  upload: client/index_deploy.html
  secure: always

- url: /dev$
  static_files: client/index.html
  upload: client/index.html
  secure: always

- url: /pay
  static_files: client/pay.html
  upload: client/pay.html
  secure: always

- url: /favicon.ico
  static_files: assets/images/ui/faviconlogo.svg
  upload: assets/images/ui/faviconlogo.svg
  secure: always
  
- url: /ClientConfig.js
  static_files: client/ClientConfig.js
  upload: client/ClientConfig.js
  secure: always

- url: /js
  static_dir: client/js
  application_readable: true
  secure: always

- url: /client
  static_dir: client
  application_readable: true
  secure: always

- url: /$
  static_dir: client
  secure: always

- url: /client/mailchimp/.*
  static_dir: client/mailchimp
  secure: always

#- url: /config
#  static_files: client/ClientConfig.js
#  upload: client/ClientConfig.js
#  secure: always

- url: /ige
  static_dir: ige
  secure: always

- url: /api/.*
  script: village.api.root
  secure: always

- url: /sheets/.*
  script: village.sheets.root
  secure: always
  
- url: /.*
  script: village.main.root
  secure: always

- url: /css2/.*
  script: village.main.root
  secure: always

- url: /js2/.*
  script: village.main.root
  secure: always

libraries:
- name: ssl
  version: latest

skip_files:
- .venv/
- libs/Crypto/
- (.*).pyc$
- .git/
- .idea/
- (.*).pack$
- \(
- ^ige/
- (.*)/.DS_Store
- (.*)/.meta$
- (.*).tmpl
- (.*).tar.gz
- ige(.*)merge
